name: Android Build & Deploy

on:
  push:
    branches:
      - feat

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          cache: true

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Set Up key.properties
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/flic.jks
          cat <<EOF > android/key.properties
          keyPassword=${{ secrets.KEY_PASSWORD }}
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=../android/flic.jks
          EOF
          echo "✅ key.properties configured successfully."

      - name: Set Up local.properties
        run: echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Set Up Play Store Secret
        run: echo "${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}" | base64 --decode > android/play_store_secret.json

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Build and Deploy
        run: make deploy-android

